### ISSUE TITLE
missing road patterns on inventory

### ISSUE THREAD

**Issue by UniqueCouch** [MapperTV/roadstuff#17] opened 2019-11-03 17:33 UTC
**FILL THIS!**
• Minecraft version: 1.14.4
• Forge version: 1.4.14-forge-28.1.79
• Road Stuff version: roadstuff-1.14.4-2.1.0
• Other mods used or modpack: World Edit

**Describe the bug**
When I press 'E' to go to select what I want from the Road Stuff 2 panel I noticed that all the road patterns are gone and missing and the only thing that is there is the cones, guardrails, road (no pattern) etc. I am on creative and wondering how to fix it.

**Comment by NightScale5755** [comment] 2019-11-03 20:23
Mapper removed the blocks. As they're so many patterns. All you have to do is place the new PaintBucket, put some yellow or white dye in it, right click it with a paintbrush. And then use the paintbrush to paint the roads.

**Comment by MapperTV** [comment] 2019-11-03 21:31
Duplicate of #13

**Closed by MapperTV** 2019-11-03 21:31 UTC

**Comment by UniqueCouch** [comment] 2019-11-03 21:50
Oh okay thanks!
